testDjango/board/urls.py
from django.urls import path
from . import views

# http://logalhost/board/
app_name = 'board'
urlpatterns = [
    path('', views.board_list, name='board_list'),
    path('write/', views.board_write, name='board_write'),
    path('detail/<int:pk>/', views.board_detail, name='board_detail'),
    path('detail/<int:pk>/delete/', views.board_delete, name='board_delete'),
    path('detail/<int:pk>/modify/', views.board_modify, name='board_modify'),
]

testDjango/home/urls.py
from django.urls import path
from . import views

# http://logalhost/home/
app_name = 'home'
urlpatterns = [
    path('', views.hello, name='hello')
]

testDjango/testProject/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static

# http://localhost/
urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', include('home.urls')),
    path('', RedirectView.as_view(url="/home/", permanent=True)),
    path('user/', include('user.urls')),
    path('board/', include('board.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

# Summernote 설정
urlpatterns += [path('summernote/', include('django_summernote.urls'))]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

testDjango/board/models.py
from django.db import models

class Board(models.Model):
    title = models.CharField(max_length=64, verbose_name='글 제목')
    contents = models.TextField(verbose_name='글 내용')
    writer = models.ForeignKey('user.User', on_delete=models.CASCADE, verbose_name='작성자')
    write_dttm = models.DateTimeField(auto_now_add=True, verbose_name='글 작성일')

    board_name = models.CharField(max_length=32, default='Python', verbose_name='게시판 종류')
    update_dttm = models.DateTimeField(auto_now=True, verbose_name='마지막 수정일')
    hits = models.PositiveIntegerField(default=0, verbose_name='조회수')

    def __str__(self):
        return self.title

    class Meta:
        db_table = 'board'
        verbose_name = '게시판'
        verbose_name_plural = '게시판'

testDjango/board/forms.py
from django import forms
from .models import Board
from django_summernote.fields import SummernoteTextField
from django_summernote.widgets import SummernoteWidget

class BoardWriteForm(forms.ModelForm):
    title = forms.CharField(
        label='글 제목',
        widget=forms.TextInput(
            attrs={
                'placeholder': '게시글 제목'
            }),
        required=True,
    )

    contents = SummernoteTextField()

    options = (
        ('Python', '파이썬 게시판'),
        ('JavaScript', '자바스크립트 게시판')
    )

    board_name = forms.ChoiceField(
        label='게시판 선택',
        widget=forms.Select(),
        choices=options
    )
    
    field_order = [
        'title',
        'board_name',
        'contents'
    ]
    
    class Meta:
        model = Board
        fields = [
            'title',
            'contents',
            'board_name'
        ]
        widgets = {
            'contents' : SummernoteWidget()
        }
        
    def clean(self):
        cleaned_data = super().clean()

        title = cleaned_data.get('title', '')
        contents = cleaned_data.get('contents', '')
        board_name = cleaned_data.get('board_name', 'Python')

        if title == '':
            self.add_error('title', '글 제목을 입력하세요.')
        elif contents == '':
            self.add_error('contents', '글 내용을 입력하세요.')
        else:
            self.title = title
            self.contents = contents
            self.board_name = board_name

testDjango/board/views.py
from django.shortcuts import render, redirect
from .forms import BoardWriteForm
from .models import Board
from user.models import User
from user.decorators import login_required
from django.shortcuts import get_object_or_404
from datetime import date, datetime, timedelta
from .pagination import pagination


def board_list(request):
    login_session = request.session.get('login_session', '')
    context = { 'login_session': login_session }

    page = pagination(request, Board)
    context.update(page)

    return render(request, 'board/board_list.html', context)


def board_detail(request, pk):
    login_session = request.session.get('login_session', '')
    context = { 'login_session': login_session }

    board = get_object_or_404(Board, id=pk)
    context['board'] = board
    
    # 글쓴이인지 확인
    if board.writer.user_id == login_session:
        context['writer'] = True
    else:
        context['writer'] = False

    response = render(request, 'board/board_detail.html', context)

    # 조회수 기능(쿠키이용)
    expire_date, now = datetime.now(), datetime.now()
    expire_date += timedelta(days=1)
    expire_date = expire_date.replace(hour=0, minute=0, second=0, microsecond=0)
    expire_date -= now
    max_age = expire_date.total_seconds()

    cookie_value = request.COOKIES.get('hitboard', '_')

    if f'_{pk}_' not in cookie_value:
        cookie_value += f'{pk}_'
        response.set_cookie('hitboard', value=cookie_value, max_age=max_age, httponly=True)
        board.hits += 1
        board.save()
    return response


@login_required
def board_write(request):
    login_session = request.session.get('login_session', '')
    context = { 'login_session': login_session }

    if request.method == 'GET':
        write_form = BoardWriteForm()
        context['forms'] = write_form
        return render(request, 'board/board_write.html', context)
    
    elif request.method == 'POST':
        write_form = BoardWriteForm(request.POST)

        if write_form.is_valid():
            writer = User.objects.get(user_id=login_session)
            board = Board(
                title=write_form.title,
                contents=write_form.contents,
                writer=writer,
                board_name=write_form.board_name
            )
            board.save()
            return redirect('/board')
        else:
            context['forms'] = write_form
            if write_form.errors:
                for value in write_form.errors.values():
                    context['error'] = value
            return render(request, 'board/board_write.html', context)


@login_required
def board_modify(request, pk):
    login_session = request.session.get('login_session', '')
    context = { 'login_session': login_session }

    board = get_object_or_404(Board, id=pk)
    context['board'] = board

    if board.writer.user_id != login_session:
        return redirect(f'/board/detail/{pk}/')

    if request.method == 'GET':
        write_form = BoardWriteForm(instance=board)
        context['forms'] = write_form
        return render(request, 'board/board_modify.html', context)
    
    elif request.method == 'POST':
        write_form = BoardWriteForm(request.POST)

        if write_form.is_valid():
            board.title=write_form.title
            board.contents=write_form.contents
            board.board_name=write_form.board_name
            board.save()
            return redirect('/board')
        else:
            context['forms'] = write_form
            if write_form.errors:
                for value in write_form.errors.values():
                    context['error'] = value
            return render(request, 'board/board_modify.html', context)


def board_delete(request, pk):
    login_session = request.session.get('login_session', '')
    board = get_object_or_404(Board, id=pk)
    if board.writer.user_id == login_session:
        board.delete()
        return redirect('/board')
    else:
        return redirect(f'/board/detail/{pk}/')

testDjango/board/templates/board/board_detail.html
{% extends 'home/index.html' %}

{% block contents %}
<div>게시판 상세보기!</div>
<div style="border: 1px black solid; margin: 20px 0px;"></div>

{% if writer %}
<a href="/board/detail/{{ board.id }}/modify/"><button>수정</button></a>
<a href="/board/detail/{{ board.id }}/delete/"><button>삭제</button></a>
{% endif %}

<div>
    게시판 종류 : {{ board.board_name }}
</div>
<div>
    작성자 : {{ board.writer }} | 작성일 : {{ board.write_dttm }} | 조회수 : {{ board.hits }}
</div>
<div>
    제목 : {{ board.title }}
</div>
<div>
    내용 : {{ board.contents|safe }}
</div>

{% endblock contents %}

testDjango/board/templates/board/board_list.html
{% extends 'home/index.html' %}

{% block contents %}
<div>게시판!</div>
<div><a href="{% url 'board:board_write' %}"><button>글쓰기</button></a></div>
<div style="border: 1px black solid; margin: 20px 0px;"></div>

<!-- 게시글 목록 -->
{% for board in boards %}
<div style="text-align: center;">
    <a href="/board/detail/{{ board.pk }}/" style="color: black;">
        <tr>
            <td>{{ board.title }}</td>
            <td>{{ board.writer.user_name }}</td>
            <td>{{ board.write_dttm|date:"Y-m-d" }}</td>
        </tr>
    </a>
</div>
{% endfor %}
<!-- 페이지 버튼 -->
{% include 'board/pagination.html' %}

{% endblock contents %}

testDjango/board/templates/board/board_modify.html
{% extends 'home/index.html' %}

{% block contents %}
<div>게시판 글 수정하기!</div>
<form action="" method='POST'>
    {% csrf_token %}

    {% for form in forms %}
    <div>
        <label for="{{ form.id_for_label }}">{{ form.label }}</label>
        {{ form }}
    </div>
    {% endfor %}
    
    {% if error %}
    {{ error }}
    {% endif %}
    <button type="submit">글 수정하기</button>
</form>
{% endblock contents %}

testDjango/board/templates/board/board_write.html
{% extends 'home/index.html' %}

{% block contents %}
<div>게시판 글쓰기!</div>
<form action="" method='POST'>
    {% csrf_token %}

    {% for form in forms %}
    <div>
        <label for="{{ form.id_for_label }}">{{ form.label }}</label>
        {{ form }}
    </div>
    {% endfor %}
    
    {% if error %}
    {{ error }}
    {% endif %}
    <button type="submit">투고하기</button>
</form>
{% endblock contents %}

testDjango/board/templates/board/pagination.html
<!-- pagination -->
<div>
    <ul class="uk-pagination uk-flex-center" uk-margin>

        <!-- 첫 페이지로 이동 -->
        <li><a class="uk-icon-link" href="?page=1" uk-icon="icon: chevron-double-left; ratio:1.3;"></a></li>

        <!-- 이전 페이지묶음으로 이동 아이콘 -->
        {% if active_previous_page_chunk %}
        <li><a href="?page={{ previous_page_chunk }}"><span uk-pagination-previous></span></a></li>
        {% else %}
        <li class="uk-disabled"><a href="#"><span uk-pagination-previous></span></a></li>
        {% endif %}

        <!-- 페이지 숫자 -->
        {% for key, value in display_page.items %}
        {% if value %}
        {% if value == now_page %}
        <li class="uk-active"><span>{{ value }}</span></li>
        {% else %}
        <li><a href="?page={{ value }}">{{ value }}</a></li>
        {% endif %}
        {% endif %}
        {% endfor %}

        <!-- 다음 페이지묶음으로 이동 아이콘 -->
        {% if active_next_page_chunk %}
        <li><a href="?page={{ next_page_chunk }}"><span uk-pagination-next></span></a></li>
        {% else %}
        <li class="uk-disabled"><a href="#"><span uk-pagination-next></span></a></li>
        {% endif %}

        <!-- 마지막 페이지로 이동 -->
        <li><a class="uk-icon-link" href="?page={{ end_page }}" uk-icon="icon: chevron-double-right; ratio:1.3;"></a></li>
    </ul>
</div>