testDjango/board/urls.py
from django.urls import path
from . import views

# http://logalhost/board/
app_name = 'board'
urlpatterns = [
    path('', views.board_list, name='board_list'),
    path('write/', views.board_write, name='board_write'),
    path('detail/<int:pk>/', views.board_detail, name='board_detail'),
    path('detail/<int:pk>/delete/', views.board_delete, name='board_delete'),
    path('detail/<int:pk>/modify/', views.board_modify, name='board_modify'),
]

testDjango/home/urls.py
from django.urls import path
from . import views

# http://logalhost/home/
app_name = 'home'
urlpatterns = [
    path('', views.hello, name='hello')
]

testDjango/testProject/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static

# http://localhost/
urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', include('home.urls')),
    path('', RedirectView.as_view(url="/home/", permanent=True)),
    path('user/', include('user.urls')),
    path('board/', include('board.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

# Summernote 설정
urlpatterns += [path('summernote/', include('django_summernote.urls'))]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

testDjango/user/urls.py
from django.urls import path
from . import views

# http://logalhost/user
app_name = 'user'
urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
]

testDjango/home/models.py
from django.db import models

# Create your models here.

testDjango/home/views.py
from django.shortcuts import render
from user.models import User
from django.http import HttpResponse

def hello(request):
    context = {}
    
    login_session = request.session.get('login_session', '')

    if login_session == '':
        context['login_session'] = False
    else:
        context['login_session'] = True

    return render(request, 'home/index.html', context)

testDjango/home/templates/home/index.html
<!DOCTYPE html>
<html lang="kr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>아기사자 성우 형섭</title>
    <link rel="stylesheet" href="../../../static/css/uikit.min.css" />
    <script src="../../../static/js/uikit.min.js"></script>
    <script src="../../../static/js/uikit-icons.min.js"></script>
</head>
<body>
    <h1>성우&형섭</h1>
    <a href="/"><button>홈으로</button></a>
    <a href="{% url 'board:board_list' %}"><button>게시판</button></a>

    {% if login_session %}
    <a href="{% url 'user:logout' %}"><button>로그아웃</button></a>
    {% else %}
    <a href="{% url 'user:login' %}"><button>로그인</button></a>
    <a href="{% url 'user:register' %}"><button>회원가입</button></a>
    {% endif %}
    
    <div style="border: 1px black solid; margin: 20px 0px;"></div>
    {% block contents %}
    {% endblock contents %}
</body>
</html>